cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    ]

myshop/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [
path('', views.product_list, name='product_list'),
path('<slug:category_slug>/', views.product_list,
name='product_list_by_category'),
path('<int:id>/<slug:slug>/', views.product_detail,
name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,unique=True)

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])
class Meta:
    ordering = ('name',)
    verbose_name = 'category'
    verbose_name_plural = 'categories'
def __str__(self):
    return self.name
class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],update_quantity=cd['update'])
    return redirect('cart:cart_detail')
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None


    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
    products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})
def product_detail(request, id, slug):
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_product_form = CartAddProductForm()
    return render(request,'shop/product/detail.html',{'product': product,'cart_product_form': cart_product_form})
# Create your views here.

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
<style>
.center {
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}
</style>
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
  <h1>Your shopping cart</h1>
  <table class="cart">
        <thead>
          <tr>
            <th>Image&nbsp</th>
            <th>Product&nbsp&nbsp</th>
            <th>Quantity&nbsp</th>
            <th>Unit price&nbsp</th>
            <th>Price&nbsp</th>
            <th>Remove&nbsp</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
            {% with product=item.product %}
              <tr>
                <td>
                  <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="..." style="height: 100px; width: auto">&nbsp
                  </a>
                </td>
                <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                <td>
                  <form action="{% url "cart:cart_add" product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}&nbsp
                    <input class="btn btn-primary" type="submit" value="Update">
                    {% csrf_token %}&nbsp
                  </form>
                </td>

                <td class="num">₹{{ item.price }}</td>
                <td class="num">₹{{ item.total_price }}&nbsp</td>

                <td><a class="btn btn-danger" href="{% url "cart:cart_remove" product.id%}" role="button">Remove</a></td>
              </tr>
            {% endwith %}
          {% endfor %}
          <p>

          </p>
          <tr class="total">
            <div class="center">
              <td><button type="button" class="btn btn-dark" style="margin-left:100;">Total Amount</button></td>
              <td colspan="1"></td>
              <td class="num" style="margin:10px"><h3>₹{{ cart.get_total_price }}</h3></td>
            </div>
          </tr>
        </tbody>
      </table>
      <p class="text-right">
        <a href="{% url "shop:product_list" %}" role="button" class="btn btn-warning">Continue shopping</a>

        <br>
        <br>
        <a>
          <a href="#" role="button" class="btn btn-success">Checkout</a>
        </a>
      </p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<html>
<head>


</head>
<body>
  <meta charset="utf-8" />
  <title>{% block title %}KitaabWala shop{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <style type="text/css">
  .bs-example {
    margin: 0px;

  }

  .navbar-brand {
    font-size: 20px;
    font-family: sans-serif;

  }

      /*---------------------------------------
         Social section
      -----------------------------------------*/
      footer {
        padding: 0px 0px 0px 0px;
        background-color: black;
        margin: 0px;
      }


      #ftr {

        padding: 20px;
      }

      .fa {

        font-size: 23px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        border-radius: 50%;
      }

      .fa:hover {
        opacity: 0.5;
        text-decoration: none;
      }

      .fa-facebook {
        background: #3B5998;
        color: white;
        margin-top: 30px;
      }

      .fa-whatsapp {
        background: #25d366;
        color: white;
      }

      .fa-twitter {
        background: #55ACEE;
        color: white;
      }

      .fa-instagram {
        background: #125688;
        color: white;
      }

      p {
        text-align: center;

      }
  </style>
<div id="header">
<a href="/" class="logo">KitaabWala shop</a>
</div>
<div id="subheader">
<div class="cart">

</div>
</div>
<div id="content">
{% block content %}
{% endblock %}
</div>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/default.jpg' %}{% endif %}" alt="..." style="height: 200px; width: auto">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p class="price">${{ product.price }}</p>
    <form action="{% url "cart:cart_add" product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input class="btn btn-primary" type="submit" value="Add to cart">
      
    </form>
    {{ product.description|linebreaks }}
  </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% for product in products %}
        <div class="item">
            <a href="{{ product.get_absolute_url }}">
                 <img src="{% if product.image %}{{ product.image.url }}{% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
            </a>
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
            <br>
              ₹{{ product.price }}
            </div>
        {% endfor %}
  </div>
{% endblock %}